const money=n=>`₹${Number(n).toLocaleString("en-IN")}`;
const discount=p=>p.originalPrice?Math.round((1-p.price/p.originalPrice)*100):0;
const qs=s=>document.querySelector(s);
const products=[...PRODUCTS].sort((a,b)=>b.dateAdded.localeCompare(a.dateAdded));

function footer(){const f=qs("#footer");if(!f)return;f.innerHTML=`<div class="footer-brand"><a class="logo" href="index.html">Outfits <span>Here</span></a><p>Discover trending fashion finds, styles and everyday essentials.</p><p>Some links are affiliate links. We may earn a commission at no extra cost to you.</p></div><div><h3>Explore</h3><a href="index.html">Home</a><a href="new-arrivals.html">New Arrivals</a><a href="trending.html">Trending</a><a href="deals.html">Deals</a></div><div><h3>Categories</h3><a href="category.html?cat=Men">Men</a><a href="category.html?cat=Women">Women</a><a href="category.html?cat=Shoes">Shoes</a><a href="category.html?cat=Accessories">Accessories</a></div><div><h3>Info</h3><a href="about.html">About</a><a href="contact.html">Contact</a><a href="privacy.html">Privacy Policy</a><a href="terms.html">Terms & Conditions</a><a href="disclosure.html">Affiliate Disclosure</a><a href="https://www.pinterest.com/" target="_blank" rel="noopener">Pinterest</a></div><div class="footer-bottom">© 2026 Outfits Here. All rights reserved.</div>`}
function card(p){return `<article class="product-card"><a class="product-image" href="product.html?id=${encodeURIComponent(p.id)}"><img loading="lazy" src="${p.image}" alt="${esc(p.name)}"><span class="badge">${esc(p.label||"Find")}</span></a><div class="product-info"><span class="product-category">${esc(p.category)} · ${esc(p.brand)}</span><a class="product-name" href="product.html?id=${encodeURIComponent(p.id)}">${esc(p.name)}</a><div class="product-desc">${esc(p.description)}</div><div class="price-row"><span class="price">${money(p.price)}</span>${p.originalPrice?`<span class="original">${money(p.originalPrice)}</span><span class="save">Save ${discount(p)}%</span>`:""}</div><button class="shop-btn" data-affiliate="${esc(p.id)}">Shop Now →</button></div></article>`}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function render(selector,list){const el=qs(selector);if(el)el.innerHTML=list.length?list.map(card).join(""):`<div class="empty">No products found yet.</div>`}
function trackClick(p){try{const data={event:"affiliate_product_click",product_id:p.id,product_name:p.name,category:p.category,timestamp:new Date().toISOString()};window.dataLayer=window.dataLayer||[];window.dataLayer.push(data);const counts=JSON.parse(localStorage.getItem("oh_clicks")||"{}");counts[p.id]=(counts[p.id]||0)+1;localStorage.setItem("oh_clicks",JSON.stringify(counts));}catch(e){}}
function bindAffiliate(){document.querySelectorAll("[data-affiliate]").forEach(b=>b.addEventListener("click",()=>{const p=products.find(x=>x.id===b.dataset.affiliate);if(p){trackClick(p);window.open(p.affiliateUrl,"_blank","noopener");}}))}
function initHome(){render("#homeTrending",products.filter(p=>p.trending).slice(0,4));render("#homeNew",products.slice(0,4));render("#homeDeals",products.filter(p=>discount(p)>=20).slice(0,4));}
function initHeader(){qs("#menuBtn")?.addEventListener("click",()=>{qs("#mobileMenu").classList.toggle("open");qs("#menuBtn").setAttribute("aria-expanded",qs("#mobileMenu").classList.contains("open"))});qs("#openSearch")?.addEventListener("click",()=>{qs("#searchDrawer").style.display="block";qs("#searchDrawer").setAttribute("aria-hidden","false");setTimeout(()=>qs("#globalSearch")?.focus(),50)});qs("#closeSearch")?.addEventListener("click",()=>{qs("#searchDrawer").style.display="none"});qs("#globalSearch")?.addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase();const hits=q?products.filter(p=>(p.name+" "+p.category+" "+p.brand+" "+p.tags.join(" ")).toLowerCase().includes(q)).slice(0,8):[];const r=qs("#searchResults");if(r)r.innerHTML=hits.map(p=>`<a class="mini-result" href="product.html?id=${p.id}"><img src="${p.image}" alt=""><span><b>${esc(p.name)}</b><small>${money(p.price)} · ${esc(p.category)}</small></span></a>`).join("")});}
function initNewsletter(){qs("#newsletterForm")?.addEventListener("submit",e=>{e.preventDefault();qs("#newsletterNote").textContent="Thanks! Your email has been saved for future updates.";e.target.reset()})}
function init(){footer();initHeader();initNewsletter();if(document.body.dataset.page==="home")initHome();bindAffiliate()}
document.addEventListener("DOMContentLoaded",init);