/* Add your real affiliate products here. Replace sample URLs/images before publishing. */
const PRODUCTS = [
  {id:"p001",name:"Men’s Relaxed Oxford Shirt",image:"https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=82",description:"Clean everyday shirt with an easy relaxed fit.",price:799,originalPrice:1499,category:"Men",brand:"Style Edit",affiliateUrl:"https://www.amazon.in/",dateAdded:"2026-09-29",tags:["shirt","men","casual","new"],featured:true,trending:true,label:"Trending"},
  {id:"p002",name:"Women’s Minimal Ribbed Top",image:"https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=82",description:"A versatile wardrobe basic for effortless outfits.",price:599,originalPrice:999,category:"Women",brand:"Style Edit",affiliateUrl:"https://www.amazon.in/",dateAdded:"2026-09-29",tags:["top","women","minimal"],featured:true,trending:true,label:"Hot Find"},
  {id:"p003",name:"Classic White Everyday Sneakers",image:"https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=82",description:"An easy-to-style sneaker for everyday looks.",price:1299,originalPrice:2499,category:"Shoes",brand:"Street Edit",affiliateUrl:"https://www.amazon.in/",dateAdded:"2026-09-29",tags:["shoes","sneakers","white"],featured:true,trending:true,label:"Best Seller"},
  {id:"p004",name:"Structured Everyday Shoulder Bag",image:"https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=82",description:"A polished carry-all for workdays and weekends.",price:899,originalPrice:1599,category:"Bags",brand:"Style Edit",affiliateUrl:"https://www.amazon.in/",dateAdded:"2026-09-28",tags:["bag","women","accessories"],featured:true,trending:true,label:"Trending"},
  {id:"p005",name:"Minimal Steel Watch",image:"https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=900&q=82",description:"Minimal wristwear that works with casual and formal looks.",price:1499,originalPrice:2999,category:"Watches",brand:"Time Edit",affiliateUrl:"https://www.amazon.in/",dateAdded:"2026-09-28",tags:["watch","accessories","minimal"],featured:true,trending:false,label:"Hot Find"},
  {id:"p006",name:"Men’s Straight Fit Denim",image:"https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=82",description:"A timeless straight-leg denim for everyday styling.",price:999,originalPrice:1799,category:"Men",brand:"Denim Edit",affiliateUrl:"https://www.amazon.in/",dateAdded:"2026-09-27",tags:["denim","jeans","men"],featured:false,trending:true,label:"New"},
  {id:"p007",name:"Women’s Oversized Blazer",image:"https://images.unsplash.com/photo-1591369822096-ffd140ec948f?auto=format&fit=crop&w=900&q=82",description:"An elevated layer for smart casual outfits.",price:1799,originalPrice:2999,category:"Women",brand:"Style Edit",affiliateUrl:"https://www.amazon.in/",dateAdded:"2026-09-27",tags:["blazer","women","office"],featured:false,trending:true,label:"Trending"},
  {id:"p008",name:"Classic Leather Belt",image:"https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=900&q=82",description:"A simple wardrobe essential with a polished finish.",price:499,originalPrice:799,category:"Accessories",brand:"Essentials Edit",affiliateUrl:"https://www.amazon.in/",dateAdded:"2026-09-26",tags:["belt","accessories","men"],featured:false,trending:false,label:"Best Deal"}
];